@baseUrl = http://localhost:8080/users
@baseAuthsUrl = http://localhost:8080/auths


### FAIL
# @name loggedUser
POST {{baseAuthsUrl}}/login
Content-Type: application/json

{
    "email":"test.test@test.com",
    "password":"password"
}

### SUCCESS
# @name loggedUser
POST {{baseAuthsUrl}}/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"1234"
}

### SUCCESS MOCK TEST
# @name loggedUser
POST {{baseAuthsUrl}}/login
Content-Type: application/json

{
    "email":"valid@email.com",
    "password":"1234"
}