@baseUrl = http://localhost:8080/users
@baseAuthsUrl = http://localhost:8080/auths


### FAIL
# @name loggedUser
POST {{baseAuthsUrl}}/login
Content-Type: application/json

{
    "username":"james",
    "password":"password"
}

### SUCCESS
# @name loggedUser
POST {{baseAuthsUrl}}/login
Content-Type: application/json

{
    "username":"test",
    "password":"1234"
}